version: "3"
services:
  db:
    image: docker.io/bitnami/mariadb:11.0
    volumes:
      - './db_data:/bitnami/mariadb'
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: CHANGE_PASSWORD
      MARIADB_DATABASE: hesk
      MARIADB_USER: hesk
      # Please change the password before deploying.
      MARIADB_PASSWORD: CHANGE_PASSWORD
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  hesk:
    depends_on:
      - db
    image: hesk_343_volume:latest
    volumes:
      - ./hesk:/srv
    ports:
      - "8080:80"
    restart: always